- name: variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Trainer: "SivaKumar"
    Duration: "10hrs"
  tasks:
  - name: print information
    ansible.builtin.debug: 
      msg: "Hi I am learning {{Course}} from trainer {{Trainer}}, Duration is {{Duration}}."