- name: conditions
  hosts: localhost
  vars_prompt:
  - name: NUMBER
    private: no
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "Given number {{NUMBER}} is less than 10"
    when: NUMBER < 10    

  - name: number is greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{NUMBER}} is greater than or equal to 10"
    when: NUMBER >= 10        